[project]
name = "dat-to-hex"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "construct==2.10.68",
    "construct-editor>=0.1.5",
]
