[project]
name = "dat-to-hex"
version = "0.0.3"
description = "Author: kotop21 :)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "construct==2.10.68",
    "construct-editor>=0.1.5",
    "tqdm>=4.67.1",
]
